services:
  app:
    depends_on:
      - api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_NEST_URL: ${NEXT_PUBLIC_NEST_URL}
        NEXT_PUBLIC_NEST_SOCKET: ${NEXT_PUBLIC_NEST_SOCKET}
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_NEST_URL=${NEXT_PUBLIC_NEST_URL}
      - NEXT_PUBLIC_NEST_SOCKET=${NEXT_PUBLIC_NEST_SOCKET}
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - app-network