@baseUrl = http://localhost:3000

# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "Thiago"
}

###
@userId = {{createUser.response.body.userId}}

###
@token = {{createUser.response.body.access_token}}

# @name getUser
GET {{baseUrl}}/user/{{userId}}
Authorization: Bearer {{token}}

###

# @name deleteUser
DELETE {{baseUrl}}/user/{{userId}}
Authorization: Bearer {{token}}